{% set version = '1.0-11' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fitdistrplus
  version: {{ version|replace("-", "_") }}

source:
  fn: fitdistrplus_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/fitdistrplus_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fitdistrplus/fitdistrplus_{{ version }}.tar.gz
  sha256: 861b986529d21a1c5de3e7e22848167704848f60b3f31770827fc8e2c79b0c8a

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: actuar, rgenoud, mc2d, gamlss.dist, knitr, knitcitations, ggplot2, GeneralizedHyperbolic
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-mass
    - r-npsurv
    - r-survival

  run:
    - r-base
    - r-mass
    - r-npsurv
    - r-survival

test:
  commands:
    - $R -e "library('fitdistrplus')"           # [not win]
    - "\"%R%\" -e \"library('fitdistrplus')\""  # [win]

about:
  home: 'MailingList: http://listes.univ-lyon1.fr/wws/info/fitdist-users; https://lbbe.univ-lyon1.fr/fitdistrplus.html,
    http://riskassessment.r-forge.r-project.org'

  license: GPL (>= 2)
  summary: Extends the fitdistr() function (of the MASS package) with several functions to help
    the fit of a parametric distribution to non-censored or censored data. Censored
    data may contain left censored, right censored and interval censored values, with
    several lower and upper bounds. In addition to maximum likelihood estimation (MLE),
    the package provides moment matching (MME), quantile matching (QME) and maximum
    goodness-of-fit estimation (MGE) methods (available only for non-censored data).
    Weighted versions of MLE, MME and QME are available. See e.g. Casella & Berger (2002).
    Statistical inference. Pacific Grove.
  license_family: GPL3

extra:
  recipe-maintainers:
    - dpryan79
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
