travis:
  secure:
    BINSTAR_TOKEN: C12yC//UpsIgW9EPUDtU+KRv/ATJ2hEb017ZAYnouKgiJMY3Gl/yOBcaypeLY0gphbN0uNxIrSlFq0XoLkV5EIiDtQxBrdKdSMYYttjJ36a47yZX1KDynL8+alCNfGCbpMgU8f7732XXJUqFeRa3QubroEYxRMu9i1QzegvyRiHAh9L+AOnEAFPSWwhOKgYaBp/j8s50GeH1eAUZnmbjvhz6vxRT+t3Eq7QP0sWdsB5EqU8B6lZlfoJPSBJHrujnFPpjpToat9HO+NdTY10PYnI/44ra+n2UDAZMyw0HHeEkNrdLEGC5PL9mZ5t/KlrgRlzLRcJV8sM/vUKbPIcB65bKzcrwXm9gjue7K2Y+tZC8fq+SsCrPliuOqQlfG7zqsnLqarBaZvnpQ0xpVAtMgfsBCZKIpqZlXvm0UCHyE46VITLlNczuKlMtmKhfPK04CFwWLeFf1VJmrBlbhx56I3XsnoHQp449609dv5lep2qJSUMmI9nzKvOdFO2dVQaulGPj4YouliTqS06Ka2Otdbf9xZZ6C+/wxRT6bxJCn7jVzky0nYPVJVkMfKgKofzZgu8AfZik3tZYCAZ5q1hYdN2HaKOCSerb/YQb2VTEqmyMxWzIZTFfBLwccW7rBvm5ItoNJxTy50bdnezGWn5KDKC/MpQo+6pmHthAhJ3glIM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
