appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: YtT6cy5CPGFNwCMw8CSW55vXwgbWw7T2/QTdzYACD8wyAJfP2kZZ0LkayOOBjyiJE7kYwvF3YIN+ggspr9+NT9BcGlZs4lAyDp8+5pHUy5Mo4SH6+uGzKiPAV0GiRhRP1jAmpmH2S2/78QuB16CUXLZf2ECy4fDC6QCSLxok9nPHUHQrU1VEhf9qil1Diqk705bK82N1jfewY6yhIDqOI+bZ9hdLyihbb7zKEKPuRTaehhKDBcGBzeT7HHPc2kNSr5ZcTxmT4SBaeCOW+K4oI6KZHvbdBMGdAxE5Yaz2db7HbOpazVKV2eVrCjuEAxVDF/AtGcpErRJ3SqN6QMNcFTpTLBpmevXgCZkderakf7jSamSTwimiWVmN63M6/4y0H1ZFP7PGDrsTsP5RT5LRPQDjnLRKVmlGk0D7QVhp4Zfif++64LE7lx2zXIyKWdGAs0m4fpQ82fdig4K31vWnONC44d8IS3L7BBwNVhfwOaHzBHofD1LIINCi0W9BOtGO4kgkpZzQUxUzSNzHC5A1RRfywO+p7zsodpQGdpjeEQoUgNOY7itTRpneRtdX+/TZCuuOfvplTELUbVEnDLz5VTheNi1ElEUiAGl+E3A0fIdmX0XQxc77Zt20waaRaXsaFhYhEAA+Qil7SzF51nq5tqsz/rnZPHudazpx7Ogz3AY=}
